// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/devtron-labs/telemetry-user-analytics/api"
	"github.com/devtron-labs/telemetry-user-analytics/client"
	"github.com/devtron-labs/telemetry-user-analytics/internal/logger"
	"github.com/devtron-labs/telemetry-user-analytics/internal/sql"
	"github.com/devtron-labs/telemetry-user-analytics/internal/sql/repository"
	"github.com/devtron-labs/telemetry-user-analytics/pkg/telemetry"
	"github.com/devtron-labs/telemetry-user-analytics/pubsub"
)

// Injectors from Wire.go:

func InitializeApp() (*App, error) {
	sugaredLogger := logger.NewSugardLogger()
	config, err := sql.GetConfig()
	if err != nil {
		return nil, err
	}
	db, err := sql.NewDbConnection(config, sugaredLogger)
	if err != nil {
		return nil, err
	}
	telemetryPlatformRepositoryImpl := repository.NewTelemetryPlatformRepositoryImpl(db)
	telemetryInstallHistoryRepositoryImpl := repository.NewTelemetryInstallHistoryRepositoryImpl(db)
	httpClient := logger.NewHttpClient()
	telemetryEventServiceImpl := telemetry.NewTelemetryEventServiceImpl(sugaredLogger, telemetryPlatformRepositoryImpl, telemetryInstallHistoryRepositoryImpl, httpClient)
	restHandlerImpl := api.NewRestHandlerImpl(sugaredLogger, telemetryEventServiceImpl)
	cronServiceImpl := telemetry.NewCronServiceImpl(sugaredLogger, telemetryPlatformRepositoryImpl, telemetryInstallHistoryRepositoryImpl, httpClient)
	muxRouter := api.NewMuxRouter(sugaredLogger, restHandlerImpl, cronServiceImpl)
	pubSubClient, err := client.NewPubSubClient(sugaredLogger)
	if err != nil {
		return nil, err
	}
	natSubscriptionImpl, err := pubsub.NewNatSubscription(pubSubClient, sugaredLogger)
	if err != nil {
		return nil, err
	}
	app := NewApp(muxRouter, sugaredLogger, db, natSubscriptionImpl)
	return app, nil
}
